### ISSUE TITLE
filter: toggle off

### ISSUE THREAD

**Issue by Hachiiki** [hongduccodedao/Bot-Music-Discord-v13#3]
**Installing**
npm install

**Node**
v17.7.2

**Affected Version**
v1.5.0

**Problem**
khi sử dụng lệnh **filter off** nó không tắt bộ lọc và chỉ gửi lỗi nhúng. **Lỗi: Không tìm thấy bộ lọc phù hợp!**
_English: when using **filter off** command it doesn't turn off the filter and just send embedding error. **Error: No matching filter found!**_

**Console error:**
No error in the console

**Comment by hongducdev** [comment]
If you want to turn off the filter, just re-enter the filter name and it will turn off.

**Comment by Hachiiki** [comment]
> If you want to turn off the filter, just re-enter the filter name and it will turn off.

oh okay.. I thought it was an error or something haha.. also in ./SlashCommands/music/skip.js 
Line: 20 the error was `interaction.reply` and should be replace `interaction.followUp`. 

Thanks, man!
